/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_menu (void)
{
  GtkWidget *menu;
  GtkWidget *fixed1;
  GtkWidget *label1_menu;
  GtkWidget *button1_gestion_de_menu;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label21;
  GtkWidget *button2_meilleur;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label22;

  menu = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (menu), _("menu"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (menu), fixed1);

  label1_menu = gtk_label_new (_("Menu"));
  gtk_widget_show (label1_menu);
  gtk_fixed_put (GTK_FIXED (fixed1), label1_menu, 112, 24);
  gtk_widget_set_size_request (label1_menu, 41, 17);

  button1_gestion_de_menu = gtk_button_new ();
  gtk_widget_show (button1_gestion_de_menu);
  gtk_fixed_put (GTK_FIXED (fixed1), button1_gestion_de_menu, 48, 56);
  gtk_widget_set_size_request (button1_gestion_de_menu, 168, 48);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button1_gestion_de_menu), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_(" Gestion de menu"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox2), label21, FALSE, FALSE, 0);

  button2_meilleur = gtk_button_new ();
  gtk_widget_show (button2_meilleur);
  gtk_fixed_put (GTK_FIXED (fixed1), button2_meilleur, 16, 120);
  gtk_widget_set_size_request (button2_meilleur, 240, 48);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button2_meilleur), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label22 = gtk_label_new_with_mnemonic (_(" Meilleur menu de la semaine"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox3), label22, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button1_gestion_de_menu, "clicked",
                    G_CALLBACK (on_button1_gestion_de_menu_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2_meilleur, "clicked",
                    G_CALLBACK (on_button2_meilleur_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (menu, menu, "menu");
  GLADE_HOOKUP_OBJECT (menu, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (menu, label1_menu, "label1_menu");
  GLADE_HOOKUP_OBJECT (menu, button1_gestion_de_menu, "button1_gestion_de_menu");
  GLADE_HOOKUP_OBJECT (menu, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (menu, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (menu, image2, "image2");
  GLADE_HOOKUP_OBJECT (menu, label21, "label21");
  GLADE_HOOKUP_OBJECT (menu, button2_meilleur, "button2_meilleur");
  GLADE_HOOKUP_OBJECT (menu, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (menu, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (menu, image3, "image3");
  GLADE_HOOKUP_OBJECT (menu, label22, "label22");

  return menu;
}

GtkWidget*
create_gestion_de_menu (void)
{
  GtkWidget *gestion_de_menu;
  GtkWidget *fixed2;
  GtkWidget *button3_ajouter;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label23;
  GtkWidget *button4_modifier;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label24;
  GtkWidget *button5_supprimer;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label25;
  GtkWidget *button7_retour;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label26;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview1;

  gestion_de_menu = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (gestion_de_menu), _("gestion de menu"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (gestion_de_menu), fixed2);

  button3_ajouter = gtk_button_new ();
  gtk_widget_show (button3_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), button3_ajouter, 16, 300);
  gtk_widget_set_size_request (button3_ajouter, 105, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button3_ajouter), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_(" Ajouter"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox4), label23, FALSE, FALSE, 0);

  button4_modifier = gtk_button_new ();
  gtk_widget_show (button4_modifier);
  gtk_fixed_put (GTK_FIXED (fixed2), button4_modifier, 128, 300);
  gtk_widget_set_size_request (button4_modifier, 105, 32);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button4_modifier), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_(" Modifier"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox5), label24, FALSE, FALSE, 0);

  button5_supprimer = gtk_button_new ();
  gtk_widget_show (button5_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed2), button5_supprimer, 240, 300);
  gtk_widget_set_size_request (button5_supprimer, 105, 32);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button5_supprimer), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_(" Supprimer"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox6), label25, FALSE, FALSE, 0);

  button7_retour = gtk_button_new ();
  gtk_widget_show (button7_retour);
  gtk_fixed_put (GTK_FIXED (fixed2), button7_retour, 488, 350);
  gtk_widget_set_size_request (button7_retour, 96, 32);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button7_retour), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_(" Retour"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox7), label26, FALSE, FALSE, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed2), scrolledwindow1, 56, 16);
  gtk_widget_set_size_request (scrolledwindow1, 472, 256);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview1);
  gtk_widget_set_size_request (treeview1, 450, 260);
  gtk_container_set_border_width (GTK_CONTAINER (treeview1), 50);

  g_signal_connect ((gpointer) button3_ajouter, "clicked",
                    G_CALLBACK (on_button3_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4_modifier, "clicked",
                    G_CALLBACK (on_button4_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) button5_supprimer, "clicked",
                    G_CALLBACK (on_button5_supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) button7_retour, "clicked",
                    G_CALLBACK (on_button7_retour_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gestion_de_menu, gestion_de_menu, "gestion_de_menu");
  GLADE_HOOKUP_OBJECT (gestion_de_menu, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (gestion_de_menu, button3_ajouter, "button3_ajouter");
  GLADE_HOOKUP_OBJECT (gestion_de_menu, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (gestion_de_menu, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (gestion_de_menu, image4, "image4");
  GLADE_HOOKUP_OBJECT (gestion_de_menu, label23, "label23");
  GLADE_HOOKUP_OBJECT (gestion_de_menu, button4_modifier, "button4_modifier");
  GLADE_HOOKUP_OBJECT (gestion_de_menu, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (gestion_de_menu, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (gestion_de_menu, image5, "image5");
  GLADE_HOOKUP_OBJECT (gestion_de_menu, label24, "label24");
  GLADE_HOOKUP_OBJECT (gestion_de_menu, button5_supprimer, "button5_supprimer");
  GLADE_HOOKUP_OBJECT (gestion_de_menu, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (gestion_de_menu, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (gestion_de_menu, image6, "image6");
  GLADE_HOOKUP_OBJECT (gestion_de_menu, label25, "label25");
  GLADE_HOOKUP_OBJECT (gestion_de_menu, button7_retour, "button7_retour");
  GLADE_HOOKUP_OBJECT (gestion_de_menu, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (gestion_de_menu, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (gestion_de_menu, image7, "image7");
  GLADE_HOOKUP_OBJECT (gestion_de_menu, label26, "label26");
  GLADE_HOOKUP_OBJECT (gestion_de_menu, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (gestion_de_menu, treeview1, "treeview1");

  return gestion_de_menu;
}

GtkWidget*
create_ajouter (void)
{
  GtkWidget *ajouter;
  GtkWidget *fixed3;
  GtkWidget *entry1_id;
  GtkWidget *entry4_entree;
  GtkWidget *entry5_plat;
  GtkWidget *entry6_dessert;
  GtkWidget *label3_jour;
  GtkWidget *label6;
  GtkWidget *button8_ajouter;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label27;
  GtkWidget *button9_afficher;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label28;
  GtkWidget *radiobutton_midi;
  GSList *radiobutton_midi_group = NULL;
  GtkWidget *radiobutton_soir;
  GtkWidget *label4_formule;
  GtkWidget *label5;
  GtkWidget *label7;
  GtkWidget *label2_id;
  GtkWidget *combobox1;
  GtkWidget *label_ajout;

  ajouter = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajouter), _("ajouter"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (ajouter), fixed3);

  entry1_id = gtk_entry_new ();
  gtk_widget_show (entry1_id);
  gtk_fixed_put (GTK_FIXED (fixed3), entry1_id, 136, 25);
  gtk_widget_set_size_request (entry1_id, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1_id), 8226);

  entry4_entree = gtk_entry_new ();
  gtk_widget_show (entry4_entree);
  gtk_fixed_put (GTK_FIXED (fixed3), entry4_entree, 136, 145);
  gtk_widget_set_size_request (entry4_entree, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4_entree), 8226);

  entry5_plat = gtk_entry_new ();
  gtk_widget_show (entry5_plat);
  gtk_fixed_put (GTK_FIXED (fixed3), entry5_plat, 136, 185);
  gtk_widget_set_size_request (entry5_plat, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5_plat), 8226);

  entry6_dessert = gtk_entry_new ();
  gtk_widget_show (entry6_dessert);
  gtk_fixed_put (GTK_FIXED (fixed3), entry6_dessert, 136, 225);
  gtk_widget_set_size_request (entry6_dessert, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6_dessert), 8226);

  label3_jour = gtk_label_new (_("Jour"));
  gtk_widget_show (label3_jour);
  gtk_fixed_put (GTK_FIXED (fixed3), label3_jour, 20, 65);
  gtk_widget_set_size_request (label3_jour, 110, 24);

  label6 = gtk_label_new (_("Plat_principal"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed3), label6, 20, 185);
  gtk_widget_set_size_request (label6, 110, 24);

  button8_ajouter = gtk_button_new ();
  gtk_widget_show (button8_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed3), button8_ajouter, 160, 280);
  gtk_widget_set_size_request (button8_ajouter, 100, 30);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button8_ajouter), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_(" Ajouter"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox8), label27, FALSE, FALSE, 0);

  button9_afficher = gtk_button_new ();
  gtk_widget_show (button9_afficher);
  gtk_fixed_put (GTK_FIXED (fixed3), button9_afficher, 160, 360);
  gtk_widget_set_size_request (button9_afficher, 100, 30);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button9_afficher), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-index", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_(" Afficher"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox9), label28, FALSE, FALSE, 0);

  radiobutton_midi = gtk_radio_button_new_with_mnemonic (NULL, _("Midi"));
  gtk_widget_show (radiobutton_midi);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton_midi, 136, 105);
  gtk_widget_set_size_request (radiobutton_midi, 88, 23);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_midi), radiobutton_midi_group);
  radiobutton_midi_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_midi));

  radiobutton_soir = gtk_radio_button_new_with_mnemonic (NULL, _("Soir"));
  gtk_widget_show (radiobutton_soir);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton_soir, 235, 105);
  gtk_widget_set_size_request (radiobutton_soir, 72, 23);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_soir), radiobutton_midi_group);
  radiobutton_midi_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_soir));

  label4_formule = gtk_label_new (_("Formule"));
  gtk_widget_show (label4_formule);
  gtk_fixed_put (GTK_FIXED (fixed3), label4_formule, 20, 105);
  gtk_widget_set_size_request (label4_formule, 110, 24);

  label5 = gtk_label_new (_("Entree"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed3), label5, 20, 145);
  gtk_widget_set_size_request (label5, 110, 24);

  label7 = gtk_label_new (_("Dessert"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed3), label7, 20, 225);
  gtk_widget_set_size_request (label7, 110, 24);

  label2_id = gtk_label_new (_("Id"));
  gtk_widget_show (label2_id);
  gtk_fixed_put (GTK_FIXED (fixed3), label2_id, 20, 25);
  gtk_widget_set_size_request (label2_id, 110, 24);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed3), combobox1, 136, 65);
  gtk_widget_set_size_request (combobox1, 160, 27);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Lundi "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Mardi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Mercredi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Jeudi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Vendredi"));

  label_ajout = gtk_label_new ("");
  gtk_widget_show (label_ajout);
  gtk_fixed_put (GTK_FIXED (fixed3), label_ajout, 112, 320);
  gtk_widget_set_size_request (label_ajout, 200, 30);

  g_signal_connect ((gpointer) button8_ajouter, "clicked",
                    G_CALLBACK (on_button8_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) button9_afficher, "clicked",
                    G_CALLBACK (on_button9_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_midi, "toggled",
                    G_CALLBACK (on_radiobutton_midi_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_soir, "toggled",
                    G_CALLBACK (on_radiobutton_soir_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajouter, ajouter, "ajouter");
  GLADE_HOOKUP_OBJECT (ajouter, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (ajouter, entry1_id, "entry1_id");
  GLADE_HOOKUP_OBJECT (ajouter, entry4_entree, "entry4_entree");
  GLADE_HOOKUP_OBJECT (ajouter, entry5_plat, "entry5_plat");
  GLADE_HOOKUP_OBJECT (ajouter, entry6_dessert, "entry6_dessert");
  GLADE_HOOKUP_OBJECT (ajouter, label3_jour, "label3_jour");
  GLADE_HOOKUP_OBJECT (ajouter, label6, "label6");
  GLADE_HOOKUP_OBJECT (ajouter, button8_ajouter, "button8_ajouter");
  GLADE_HOOKUP_OBJECT (ajouter, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (ajouter, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (ajouter, image8, "image8");
  GLADE_HOOKUP_OBJECT (ajouter, label27, "label27");
  GLADE_HOOKUP_OBJECT (ajouter, button9_afficher, "button9_afficher");
  GLADE_HOOKUP_OBJECT (ajouter, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (ajouter, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (ajouter, image9, "image9");
  GLADE_HOOKUP_OBJECT (ajouter, label28, "label28");
  GLADE_HOOKUP_OBJECT (ajouter, radiobutton_midi, "radiobutton_midi");
  GLADE_HOOKUP_OBJECT (ajouter, radiobutton_soir, "radiobutton_soir");
  GLADE_HOOKUP_OBJECT (ajouter, label4_formule, "label4_formule");
  GLADE_HOOKUP_OBJECT (ajouter, label5, "label5");
  GLADE_HOOKUP_OBJECT (ajouter, label7, "label7");
  GLADE_HOOKUP_OBJECT (ajouter, label2_id, "label2_id");
  GLADE_HOOKUP_OBJECT (ajouter, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (ajouter, label_ajout, "label_ajout");

  return ajouter;
}

GtkWidget*
create_supprimer (void)
{
  GtkWidget *supprimer;
  GtkWidget *fixed5;
  GtkWidget *label18_id;
  GtkWidget *combo_supprimer;
  GtkWidget *button12_supprimer;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label30;
  GtkWidget *button13_afficher;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label31;
  GtkWidget *label_sup;

  supprimer = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (supprimer), _("supprimer"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (supprimer), fixed5);

  label18_id = gtk_label_new (_("Id"));
  gtk_widget_show (label18_id);
  gtk_fixed_put (GTK_FIXED (fixed5), label18_id, 16, 25);
  gtk_widget_set_size_request (label18_id, 50, 30);

  combo_supprimer = gtk_combo_box_new_text ();
  gtk_widget_show (combo_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed5), combo_supprimer, 80, 25);
  gtk_widget_set_size_request (combo_supprimer, 80, 30);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_supprimer), _("id"));

  button12_supprimer = gtk_button_new ();
  gtk_widget_show (button12_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed5), button12_supprimer, 40, 72);
  gtk_widget_set_size_request (button12_supprimer, 105, 32);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button12_supprimer), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label30 = gtk_label_new_with_mnemonic (_(" Supprimer"));
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox10), label30, FALSE, FALSE, 0);

  button13_afficher = gtk_button_new ();
  gtk_widget_show (button13_afficher);
  gtk_fixed_put (GTK_FIXED (fixed5), button13_afficher, 240, 176);
  gtk_widget_set_size_request (button13_afficher, 105, 32);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button13_afficher), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label31 = gtk_label_new_with_mnemonic (_(" Quitter"));
  gtk_widget_show (label31);
  gtk_box_pack_start (GTK_BOX (hbox11), label31, FALSE, FALSE, 0);

  label_sup = gtk_label_new ("");
  gtk_widget_show (label_sup);
  gtk_fixed_put (GTK_FIXED (fixed5), label_sup, 24, 120);
  gtk_widget_set_size_request (label_sup, 200, 32);

  g_signal_connect ((gpointer) button12_supprimer, "clicked",
                    G_CALLBACK (on_button12_supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) button13_afficher, "clicked",
                    G_CALLBACK (on_button13_afficher_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (supprimer, supprimer, "supprimer");
  GLADE_HOOKUP_OBJECT (supprimer, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (supprimer, label18_id, "label18_id");
  GLADE_HOOKUP_OBJECT (supprimer, combo_supprimer, "combo_supprimer");
  GLADE_HOOKUP_OBJECT (supprimer, button12_supprimer, "button12_supprimer");
  GLADE_HOOKUP_OBJECT (supprimer, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (supprimer, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (supprimer, image10, "image10");
  GLADE_HOOKUP_OBJECT (supprimer, label30, "label30");
  GLADE_HOOKUP_OBJECT (supprimer, button13_afficher, "button13_afficher");
  GLADE_HOOKUP_OBJECT (supprimer, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (supprimer, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (supprimer, image11, "image11");
  GLADE_HOOKUP_OBJECT (supprimer, label31, "label31");
  GLADE_HOOKUP_OBJECT (supprimer, label_sup, "label_sup");

  return supprimer;
}

GtkWidget*
create_meilleur (void)
{
  GtkWidget *meilleur;
  GtkWidget *fixed6;
  GtkWidget *button_meilleur;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label20;
  GtkWidget *label_meilleur;
  GtkWidget *button_retour;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label35;

  meilleur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (meilleur), _("meilleur"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (meilleur), fixed6);

  button_meilleur = gtk_button_new ();
  gtk_widget_show (button_meilleur);
  gtk_fixed_put (GTK_FIXED (fixed6), button_meilleur, 48, 40);
  gtk_widget_set_size_request (button_meilleur, 312, 40);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button_meilleur), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label20 = gtk_label_new_with_mnemonic (_("Le meilleur menu de la semaine !"));
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (hbox1), label20, FALSE, FALSE, 0);

  label_meilleur = gtk_label_new ("");
  gtk_widget_show (label_meilleur);
  gtk_fixed_put (GTK_FIXED (fixed6), label_meilleur, 32, 96);
  gtk_widget_set_size_request (label_meilleur, 352, 72);

  button_retour = gtk_button_new ();
  gtk_widget_show (button_retour);
  gtk_fixed_put (GTK_FIXED (fixed6), button_retour, 320, 168);
  gtk_widget_set_size_request (button_retour, 85, 30);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button_retour), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label35 = gtk_label_new_with_mnemonic (_(" Retour"));
  gtk_widget_show (label35);
  gtk_box_pack_start (GTK_BOX (hbox14), label35, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_meilleur, "clicked",
                    G_CALLBACK (on_button_meilleur_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_retour, "clicked",
                    G_CALLBACK (on_button_retour_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (meilleur, meilleur, "meilleur");
  GLADE_HOOKUP_OBJECT (meilleur, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (meilleur, button_meilleur, "button_meilleur");
  GLADE_HOOKUP_OBJECT (meilleur, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (meilleur, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (meilleur, image1, "image1");
  GLADE_HOOKUP_OBJECT (meilleur, label20, "label20");
  GLADE_HOOKUP_OBJECT (meilleur, label_meilleur, "label_meilleur");
  GLADE_HOOKUP_OBJECT (meilleur, button_retour, "button_retour");
  GLADE_HOOKUP_OBJECT (meilleur, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (meilleur, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (meilleur, image14, "image14");
  GLADE_HOOKUP_OBJECT (meilleur, label35, "label35");

  return meilleur;
}

GtkWidget*
create_modifier (void)
{
  GtkWidget *modifier;
  GtkWidget *fixed7;
  GtkWidget *entry4;
  GtkWidget *entry5;
  GtkWidget *entry6;
  GtkWidget *combo_modifier;
  GtkWidget *fixed8;
  GtkWidget *radiobutton2_soir;
  GSList *radiobutton2_soir_group = NULL;
  GtkWidget *radiobutton1_midi;
  GtkWidget *label12;
  GtkWidget *label18;
  GtkWidget *label19;
  GtkWidget *label16;
  GtkWidget *label15;
  GtkWidget *label17;
  GtkWidget *button10_modifier;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label33;
  GtkWidget *button11_afficher;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label34;
  GtkWidget *combobox3;
  GtkWidget *label_mod;

  modifier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifier), _("modifier"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (modifier), fixed7);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed7), entry4, 120, 140);
  gtk_widget_set_size_request (entry4, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed7), entry5, 120, 180);
  gtk_widget_set_size_request (entry5, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed7), entry6, 120, 220);
  gtk_widget_set_size_request (entry6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  combo_modifier = gtk_combo_box_new_text ();
  gtk_widget_show (combo_modifier);
  gtk_fixed_put (GTK_FIXED (fixed7), combo_modifier, 120, 20);
  gtk_widget_set_size_request (combo_modifier, 160, 27);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_fixed_put (GTK_FIXED (fixed7), fixed8, 192, 256);
  gtk_widget_set_size_request (fixed8, 50, 50);

  radiobutton2_soir = gtk_radio_button_new_with_mnemonic (NULL, _("Soir"));
  gtk_widget_show (radiobutton2_soir);
  gtk_fixed_put (GTK_FIXED (fixed7), radiobutton2_soir, 216, 104);
  gtk_widget_set_size_request (radiobutton2_soir, 64, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2_soir), radiobutton2_soir_group);
  radiobutton2_soir_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2_soir));

  radiobutton1_midi = gtk_radio_button_new_with_mnemonic (NULL, _("Midi"));
  gtk_widget_show (radiobutton1_midi);
  gtk_fixed_put (GTK_FIXED (fixed7), radiobutton1_midi, 120, 104);
  gtk_widget_set_size_request (radiobutton1_midi, 64, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1_midi), radiobutton2_soir_group);
  radiobutton2_soir_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1_midi));

  label12 = gtk_label_new (_("Id"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed7), label12, 2, 20);
  gtk_widget_set_size_request (label12, 110, 24);

  label18 = gtk_label_new (_("Jour"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed7), label18, 2, 60);
  gtk_widget_set_size_request (label18, 110, 24);

  label19 = gtk_label_new (_("Formule"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed7), label19, 2, 100);
  gtk_widget_set_size_request (label19, 110, 24);

  label16 = gtk_label_new (_("Entree"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed7), label16, 2, 140);
  gtk_widget_set_size_request (label16, 110, 24);

  label15 = gtk_label_new (_("Plat_principal"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed7), label15, 2, 180);
  gtk_widget_set_size_request (label15, 110, 24);

  label17 = gtk_label_new (_("Dessert"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed7), label17, 2, 220);
  gtk_widget_set_size_request (label17, 110, 24);

  button10_modifier = gtk_button_new ();
  gtk_widget_show (button10_modifier);
  gtk_fixed_put (GTK_FIXED (fixed7), button10_modifier, 136, 272);
  gtk_widget_set_size_request (button10_modifier, 110, 30);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button10_modifier), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label33 = gtk_label_new_with_mnemonic (_(" Modifier"));
  gtk_widget_show (label33);
  gtk_box_pack_start (GTK_BOX (hbox12), label33, FALSE, FALSE, 0);

  button11_afficher = gtk_button_new ();
  gtk_widget_show (button11_afficher);
  gtk_fixed_put (GTK_FIXED (fixed7), button11_afficher, 280, 344);
  gtk_widget_set_size_request (button11_afficher, 110, 30);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button11_afficher), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-media-play", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label34 = gtk_label_new_with_mnemonic (_(" Afficher"));
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (hbox13), label34, FALSE, FALSE, 0);

  combobox3 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox3);
  gtk_fixed_put (GTK_FIXED (fixed7), combobox3, 120, 60);
  gtk_widget_set_size_request (combobox3, 160, 27);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("Lundi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("Mardi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("Mercredi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("Jeudi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("Vendredi"));

  label_mod = gtk_label_new ("");
  gtk_widget_show (label_mod);
  gtk_fixed_put (GTK_FIXED (fixed7), label_mod, 72, 312);
  gtk_widget_set_size_request (label_mod, 250, 30);

  g_signal_connect ((gpointer) button10_modifier, "clicked",
                    G_CALLBACK (on_button10_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) button11_afficher, "clicked",
                    G_CALLBACK (on_button11_afficher_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifier, modifier, "modifier");
  GLADE_HOOKUP_OBJECT (modifier, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (modifier, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (modifier, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (modifier, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (modifier, combo_modifier, "combo_modifier");
  GLADE_HOOKUP_OBJECT (modifier, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (modifier, radiobutton2_soir, "radiobutton2_soir");
  GLADE_HOOKUP_OBJECT (modifier, radiobutton1_midi, "radiobutton1_midi");
  GLADE_HOOKUP_OBJECT (modifier, label12, "label12");
  GLADE_HOOKUP_OBJECT (modifier, label18, "label18");
  GLADE_HOOKUP_OBJECT (modifier, label19, "label19");
  GLADE_HOOKUP_OBJECT (modifier, label16, "label16");
  GLADE_HOOKUP_OBJECT (modifier, label15, "label15");
  GLADE_HOOKUP_OBJECT (modifier, label17, "label17");
  GLADE_HOOKUP_OBJECT (modifier, button10_modifier, "button10_modifier");
  GLADE_HOOKUP_OBJECT (modifier, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (modifier, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (modifier, image12, "image12");
  GLADE_HOOKUP_OBJECT (modifier, label33, "label33");
  GLADE_HOOKUP_OBJECT (modifier, button11_afficher, "button11_afficher");
  GLADE_HOOKUP_OBJECT (modifier, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (modifier, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (modifier, image13, "image13");
  GLADE_HOOKUP_OBJECT (modifier, label34, "label34");
  GLADE_HOOKUP_OBJECT (modifier, combobox3, "combobox3");
  GLADE_HOOKUP_OBJECT (modifier, label_mod, "label_mod");

  return modifier;
}

